#!/usr/bin/env bash
# This script reads /etc/passwd using a while loop and IFS
# It tells a story about each user in the system

# Set the Internal Field Separator to colon
IFS=:

# Read /etc/passwd line by line
while read -r username password uid gid userinfo homedir shell
do
    # Display formatted output
    echo "The user $username is part of the $gid gang, lives in $homedir and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $userinfo"
done < /etc/passwd

