#!/usr/bin/env bash
# This script tells the story of /etc/passwd users

while IFS=: read -r username _ userid group_id home shell comment
do
    # If some fields are empty, assign default values
    [ -z "$group_id" ] && group_id="unknown"
    [ -z "$home" ] && home="unknown"
    [ -z "$shell" ] && shell="unknown"
    [ -z "$comment" ] && comment="$username"

    echo "The user $username is part of $group_id gang, lives in $home and rides $shell. $userid's place is protected by the passcode x, more info about the user here: $comment"
done < /etc/passwd

