#!/usr/bin/env bash
# This script tells the story of /etc/passwd users

while IFS=: read -r username password userid group_id comment home shell
do
    # Default the comment to username if empty
    [ -z "$comment" ] && comment="$username"

    echo "The user $username is part of $group_id gang, lives in $home and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $comment"
done < /etc/passwd

