#!/usr/bin/env bash
# This script displays Best School 10 times, and says Hi on the 9th iteration

counter=1

while [ $counter -le 10 ]
do
    echo "Best School"

    if [ $counter -eq 9 ]
    then
        echo "Hi"
    fi

    counter=$((counter + 1))
done

